name: Sync subrepos via subtree

on:
  push:
    branches: [main]
  # workflow_dispatch:
  repository_dispatch:
    types: [update-from-subrepo, update-from-subrepo-number-2]


jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main-repo-subtrees
        uses: actions/checkout@v4

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup remotes
        run: |
          echo "Setting up subrepo remotes..."
          git remote add subrepo https://x-access-token:${{ secrets.MLOPS_PROD_TOKEN }}@github.com/anafsouza/subrepo.git || true
          git remote add subrepo-number-2 https://x-access-token:${{ secrets.MLOPS_PROD_TOKEN }}@github.com/anafsouza/subrepo-number-2.git || true

      - name: Pull matching subtree
        run: |
          echo "Starting subtree sync..."

          EVENT="${{ github.event_name }}"
          ACTION="${{ github.event.action }}"
          CHANGED_PATH=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | head -n 1)

          echo "Subrepo: dispatch OR push that modified subrepo/"
          if [[ "$ACTION" == "update-from-subrepo" || ( "$EVENT" == "push" && "$CHANGED_PATH" == subrepo* ) ]]; then
            echo "Syncing subrepo..."
            git fetch subrepo main
            git subtree pull --prefix=subrepo subrepo main --squash || echo "Nothing to pull"

          echo "Subrepo-number-2: dispatch OR push that modified subrepo-number-2/"
          elif [[ "$ACTION" == "update-from-subrepo-number-2" || ( "$EVENT" == "push" && "$CHANGED_PATH" == subrepo-number-2* ) ]]; then
            echo "Syncing subrepo-number-2..."
            git fetch subrepo-number-2 main
            git subtree pull --prefix=subrepo-number-2 subrepo-number-2 main --squash || echo "Nothing to pull"

          else
            echo "No matching subtree to sync or unknown trigger."
            exit 0
          fi

      - name: Push changes if any
        run: |
          echo "Checking for changes..."
          git diff --quiet || (git commit -am "Update subtree via CI" && git push origin main)
