name: Sync subrepos via subtree

on:
  # push:
  #   branches: [main]
  # workflow_dispatch:
  repository_dispatch:
    types: [update-from-subrepo, update-from-subrepo-number-2]


jobs:
  sync-subtrees:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.MLOPS_PROD_TOKEN }}


      - name: Set up Git config
        env:
          GH_USER: ${{ secrets.USER }}
          GH_EMAIL: ${{ secrets.EMAIL }}
        run: |
          git config user.name $GH_USER
          git config user.email $GH_EMAIL

      - name: Add remotes
        run: make add-remotes

      - name: Add subtrees if needed
        run: make add-subtrees

      - name: Sync subtrees
        run: |
          echo "Starting subtree sync..."

          EVENT="${{ github.event_name }}"
          ACTION="${{ github.event.action }}"
          CHANGED_PATH=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | head -n 1)

          if [[ "$ACTION" == "update-from-subrepo" ]]; then
            make pull-subrepo
          elif [[ "$ACTION" == "update-from-subrepo-number-2" ]]; then
            make pull-subrepo-number-2
          else
            echo "No matching subtree to sync or unknown trigger."
          fi
        # run: |
        #   echo "Starting subtree sync..."

        #   EVENT="${{ github.event_name }}"
        #   ACTION="${{ github.event.action }}"
        #   CHANGED_PATH=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | head -n 1)

        #   if [[ "$ACTION" == "update-from-subrepo" || ( "$EVENT" == "push" && "$CHANGED_PATH" == subrepo* ) ]]; then
        #     make pull-subrepo
        #   elif [[ "$ACTION" == "update-from-subrepo-number-2" || ( "$EVENT" == "push" && "$CHANGED_PATH" == subrepo-number-2* ) ]]; then
        #     make pull-subrepo-number-2
        #   else
        #     echo "No matching subtree to sync or unknown trigger."
        #   fi


      - name: Commit and push if there are changes
        # env:
        #   GH_USER: ${{ secrets.USER }}
        #   GH_EMAIL: ${{ secrets.EMAIL }}
          # git config user.name $GH_USER
          # git config user.email $GH_EMAIL
        run: |
          git push
  
      # git add .
      # git commit -m "chore: sync from subrepos"
      # git push 
      
        # if [ -n "$(git status --porcelain)" ]; then
        # else
        #   echo "No changes to commit."
          # fi


