name: Sync subrepos via subtree

on:
  push:
    branches: [main]
  # workflow_dispatch:
  repository_dispatch:
    types: [update-from-subrepo, update-from-subrepo-number-2]


jobs:
  sync-subtrees:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Git config
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Add remotes
        run: make add-remotes

      - name: Sync subtrees
        run: |
          echo "Starting subtree sync..."

          EVENT="${{ github.event_name }}"
          ACTION="${{ github.event.action }}"
          CHANGED_PATH=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | head -n 1)

          if [[ "$ACTION" == "update-from-subrepo" || ( "$EVENT" == "push" && "$CHANGED_PATH" == subrepo* ) ]]; then
            make pull-subrepo
          elif [[ "$ACTION" == "update-from-subrepo-number-2" || ( "$EVENT" == "push" && "$CHANGED_PATH" == subrepo-number-2* ) ]]; then
            make pull-subrepo-number-2
          else
            echo "No matching subtree to sync or unknown trigger."
          fi


      - name: Push changes if any
        run: |
          echo "Checking for changes..."
          git diff --quiet || (git commit -am "Update subtree via CI" && git push origin main)
